// <auto-generated />
using DespenzaLib.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DespenzaLib.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DespenzaLib.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("DespenzaLib.RecipeLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("RecipeId")
                        .HasColumnType("int");

                    b.Property<int>("WareId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.HasIndex("WareId");

                    b.ToTable("RecipeLine");
                });

            modelBuilder.Entity("DespenzaLib.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("UserType").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DespenzaLib.Wares", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)");

                    b.Property<decimal>("KiloPrice")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Wares");

                    b.HasDiscriminator().HasValue("Wares");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DespenzaLib.Admin", b =>
                {
                    b.HasBaseType("DespenzaLib.User");

                    b.HasDiscriminator().HasValue("Admin");
                });

            modelBuilder.Entity("DespenzaLib.Apprentice", b =>
                {
                    b.HasBaseType("DespenzaLib.User");

                    b.HasDiscriminator().HasValue("Apprentice");
                });

            modelBuilder.Entity("DespenzaLib.Baker", b =>
                {
                    b.HasBaseType("DespenzaLib.User");

                    b.HasDiscriminator().HasValue("Baker");
                });

            modelBuilder.Entity("DespenzaLib.Ingredients", b =>
                {
                    b.HasBaseType("DespenzaLib.Wares");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasDiscriminator().HasValue("Ingredients");
                });

            modelBuilder.Entity("DespenzaLib.Product", b =>
                {
                    b.HasBaseType("DespenzaLib.Wares");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<decimal>("SalePrice")
                        .HasColumnType("decimal(65,30)");

                    b.HasIndex("RecipeId");

                    b.ToTable("Wares", t =>
                        {
                            t.Property("RecipeId")
                                .HasColumnName("Product_RecipeId");
                        });

                    b.HasDiscriminator().HasValue("Product");
                });

            modelBuilder.Entity("DespenzaLib.SemiProduct", b =>
                {
                    b.HasBaseType("DespenzaLib.Wares");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.HasIndex("RecipeId");

                    b.HasDiscriminator().HasValue("SemiProduct");
                });

            modelBuilder.Entity("DespenzaLib.RecipeLine", b =>
                {
                    b.HasOne("DespenzaLib.Recipe", null)
                        .WithMany("Lines")
                        .HasForeignKey("RecipeId");

                    b.HasOne("DespenzaLib.Wares", "Ware")
                        .WithMany()
                        .HasForeignKey("WareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ware");
                });

            modelBuilder.Entity("DespenzaLib.Product", b =>
                {
                    b.HasOne("DespenzaLib.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("DespenzaLib.SemiProduct", b =>
                {
                    b.HasOne("DespenzaLib.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("DespenzaLib.Recipe", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
